server:
  port: 9001

spring:
  profiles:
    active: dev
  http:
    encoding:
      force: true
  activiti:
    check-process-definitions: false
  application:
    name: seven-system-service #服务名称,即serviceId
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0 #将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
#  zipkin:
#    base-url: http://localhost:9411/  # 指定了 Zipkin 服务器的地址
#    enabled: true
#    sender:
#      type: web

#配置actuator的相关配置
#info:
#  blog-url: http://blog.battcn.com
#  author: dragon

#加载所有的端点/默认只加载了 info / health
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: false # 可以关闭制定的端点

# 路径映射，将 health 路径映射成 rest_health 那么在访问 health 路径将为404，因为原路径已经变成 rest_health 了，一般情况下不建议使用
# management.endpoints.web.path-mapping.health=rest_health
