server:
  port: 9001                             # 端口号
  servlet:
    context-path: /schedule/api

logging:
  config: classpath:logback-dev.xml      # 日志读取logback-dev.xml 文件

eureka:                                  # 配置Eureka Server 信息
  client:
    register-with-eureka: false          # false表示不向注册中心注册自己
    fetch-registry: false                # false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检测服务
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/
  instance:                              # 自定义实例编号
    instance-id: ${eureka.instance.ip-address}:${spring.application.name}:${server.port}
    #hostname: eureka7001.com            # Eureka 服务端的实例名称
    prefer-ip-address: true              # 优先使用IP地址方式进行注册服务
    ip-address: 127.0.0.1                # 配置使用指定IP

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/seven_db?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      pool-name: pool-vscloud
      connectionTestQuery: SELECT 1
      maximum-pool-size: 3
      minimum-idle: 10
      idle-timeout: 6000000
      connection-timeout: 1800000

#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml, /mapper/*/*Mapper.xml
  #实体扫描,多个package用逗号或者分号分隔
  typeAliasesPackage:
  typeEnumsPackage:
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    # 可选参数（默认mysql） MYSQL->`mysql` ORACLE->`oracle` DB2->`db2` H2->`h2`
    # HSQL->`hsql` SQLITE->`sqlite` POSTGRE->`postgresql` SQLSERVER2005->`sqlserver2005`
    # SQLSERVER->`sqlserver`
    db-type: mysql
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator:
    #逻辑删除配置
    logic-delete-value: 0
    logic-not-delete-value: 1
    #自定义填充策略接口实现
    #meta-object-handler:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false


